### PR TITLE
Add data storage from form element

### PR DESCRIPTION
**Pull request by Yacoubou-seidou**
### Add data storage from the form element
- Form data save on change
- Data save as object
- Data load on reload page

### CODE REVIEW

**Review by wayungi — COMMENTED** [review]
Hi @Yacoubou-seidou , 
image
While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌  ❌ 

- [ ] You have submitted a project with missing parts of the [README template](https://github.com/microverseinc/readme-template). Please fill in all parts of this document

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Yacoubou-seidou** [comment]
@wayungi Please check my README and let me know what is missing

**Comment by medaminedev66** [comment]
Hello @Yacoubou-seidou  👋,

_This is an additional review as a result of the second opinion request._

The Key Features section is the only part I can see missing from your Readme. Please add it and submit a new review request in your dashboard.

Keep rocking 🚀!

**Comment by Yacoubou-seidou** [comment]
@medaminedev66  Thanks you for your  feedback !

**Review by AbayomiOlaoye — APPROVED** [review]
Hi @Yacoubou-seidou :wave:, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

applause

## Highlights
- Pair-programming :heavy_check_mark: 
- User input preservation works well :heavy_check_mark: 
- Linter checks are passing :heavy_check_mark: 
- Professional ReadMe documentation :heavy_check_mark: 
- Organized code :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
